import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";
import Footer from "@/components/Footer";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next Gadget",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Auth + Theme Providers */}
        <Providers>
          <ThemeProvider
            attribute="data-theme"
            defaultTheme="light"
            enableSystem
          >
            <Navbar />
            
            {/* Page Content */}
            <main>{children}</main>

            {/* ✅ Global Toast Notifications */}
            <Toaster position="top-right" reverseOrder={false} />

            <Footer />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
